### ISSUE TITLE
Pingu is playing in the Amateur Series

### ISSUE THREAD

**Issue by GrahamCCRL** [WillChing01/Pingu#109]
I don't have any way of contacting you.

Live broadcast here:

https://ccrl.live/16073

**Comment by WillChing01** [comment]
Thanks for letting me know, and many thanks to the CCRL team for testing Pingu!

**Comment by GrahamCCRL** [comment]
*104TH AMATEUR SERIES (Division 9)*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2023.cgb book
12 minutes with 8 second increments.
4 cycles 52 rounds
All engines 1CPU (64-bit where available)

*The top engine will gain automatic promotion. Any other changes of
division will be at my discretion and may not necessarily involve playoff
matches.*

*Participants*

Tantabus 2.0.0 64-bit (promoted)
Rengar 1.3.0 64-bit (promoted)
Admete 1.5.0 64-bit (promoted)
FoxSEE 8.2.0 64-bit (promoted)
Fornax 4 64-bit (promoted)
Pingu 2.0.0 64-bit(promoted)
Waxman 2022 (promoted)
Ares 2.1.15 64-bit (promoted)
Prophet 4.3 64-bit (promoted)
Anka 0.6.3 64-bit (promoted)
SoFCheck 0.9.1 beta 64-bit (promoted) (02-2022)
Shen Yu 2.0.1 64-bit (promoted)
Clarity 2.0.0 64-bit (promoted)
Lynx 1.0.0 64-bit (new)


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16064

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16064

Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
*MONSTER IN THE WASTELAND*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2023.cgb book
12 minutes with 8 second increments.
4 cycles 72 rounds
All engines 1CPU (64-bit where available)


*Participants*

Sirius 5.0.0 64-bit
RookieMonster 1.9.9 64-bit
CM10th Pestilence
Reckless 0.3.0 64-bit
Myrddin 0.90 64-bit
Rengar 1.3.0 64-bit
Raven 1.30 64-bit
Pingu 2.0.0 64-bit
Lux 4.0 64-bit
Luna 2.0.0 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16073

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16073

Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
*THE PIRATE CODEX*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2023.cgb book
12 minutes with 8 second increments.
6 cycles 54 rounds
All engines 1CPU (64-bit where available)


*Participants*

Sirius 5.0 64-bit
RookieMonster 1.9.9 64-bit
Rengar 1.3.0 64-bit
Myrddin 0.90 64-bit
Betsabe II 2023 64-bit
Pingu 2.0.0 64-bit
Raven 1.30 64-bit
Jellyfish 1.1 64-bit
Jumbo 0.7.0 64-bit
Ghost 3.1 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16074

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16074

Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Sun, Jan 28, 2024 at 4:24 PM
Subject: NewTournament
To: Peter Osterlund ***@***.***>, ***@***.***>, Alex
Brunetti ***@***.***>, mar ***@***.***>, <
***@***.***>, Erin Dame ***@***.***>, Onariq <
***@***.***>, Steven Griffin ***@***.***>, John Merlino <
***@***.***>


*JOANN'S JABBERWOCKIES v LANA'S LEGION*

Ryzen 5950x
ChessGUI
256mb hash each where possible
3-4-5 piece tablebases
Ponder off
GBSelect2023.cgb book
12 minutes with 8 second increments
Engines on each board will play a 12 game match
All engines 1CPU (64-bit where possible)

*JOANN'S JABBERWOCKIES v LANA'S LEGION*

*(0.0-0.0)* Stormphrax 4.0.0 64-bit v Starzix 4.0 64-bit
*(0.0-0.0)* Texel 1.11 64-bit v Altair 6.0.0 64-bit
*(0.0-0.0)* Cheng 4.44 64-bit v Protej 0.6.6 64-bit
*(0.0-0.0)* Pedantic 0.6.2 64-bit v GOOB 1.8.9 64-bit
*(0.0-0.0)* Bagatur 4.1 64-bit v Princhess 0.15.1 64-bit
*(0.0-0.0)* 4ku 4.0 64-bit v Amoeba 3.4 64-bit
*(0.0-0.0)* Reckless 0.4.0 64-bit v Zangdar 2.24 64-bit
*(0.0-0.0)* ice4 4.0 64-bit v Ynode 0132 64-bit
*(0.0-0.0)* Pingu 3.0.0 v Seawall 20231015 64-bit
*(0.0-0.0)* RookieMonster 1.9.9 64-bit v Rengar 1.3.0 64-bit
*(0.0-0.0)* Cyrano 0.6b17 64-bit v Myrddin 0.90 64-bit
*(0.0-0.0)* Raven 1.30 64-bit v Lynx 1.2.0 64-bit
*(0.0-0.0)* Fatalii 0.6.0 v Eubos 3.0.0 64-bit


*Current Match Score* *(based on board by board results)*

*0.0 - JoAnn's Jabberwockies*
*0.0 - Lana's Legion*

Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16074

**Comment by GrahamCCRL** [comment]
---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Sat, Feb 3, 2024 at 6:25 PM
Subject: New Tournament
To: Fons Bluemers ***@***.***>, Andres Valverde <
***@***.***>, Richard Pijl ***@***.***>,
***@***.***>, ***@***.***>, ***@***.***>,
Rasmus%20Althoff%20 ***@***.***>, matthiaslang/jackychess <
***@***.***>, <
***@***.***>, Technochess ***@***.***>


*SWISS 2024-II*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2023.cgb book
12 minutes with 8 second increments
7 rounds + 84 games
230 Elo spread


*Participants*

Vengeance 3.0.0 64-bit
Cadie 1.5 64-bit
Zangdar 2.24 64-bit
Ynode 0132 64-bit
ice4 4.0 64-bit
Dirty CUCUMBER 64-bit
Reckless 0.4.0 64-bit
Leorik 2.5 64-bit
The Baron 3.45 64-bit
Jet 1.1 64-bit
OliThink 5.10.5 64-bit
Clovis III 64-bit
------------------------------------------
Cheers 0.3.0 64-bit
Tornado 8.0 64-bit
Seawall 20231015 64-bit
Inanis 1.2.0 64-bit
Pingu 3.0.0 64-bit
Coiled 1.2 NoNNUE 64-bit
Dumb 2.0 64-bit
Mess 0.3.0 64-bit
Odonata 0.70 64-bit
KnightX 3.9 64-bit
JackyChess 23.12 64-bit
CT800 1.45 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16074

**Comment by GrahamCCRL** [comment]
---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Thu, Feb 15, 2024 at 6:58 AM
Subject: 106th Amateur Series Division 7
To: Richard Pijl ***@***.***>, ***@***.***>, <
***@***.***>, ***@***.***>,
jonathanmcdermid/Clovis <
***@***.***>


106TH AMATEUR SERIES (Division 7)

The Baron 3.45 64-bit (relegated)
Cadie 1.5 64-bit (relegated)
Jet 1.1 64-bit (new)
OliThink 5.10.5 64-bit (relegated)
Cheers 0.3.0 64-bit
Weiawaga 5.0 64-bit (2022-04)
Clovis III 64-bit
Seawall 20231015 64-bit
Shallow 5.0 64-bit
Inanis 1.2.0 64-bit
Pingu 3.0.0 64-bit
Odonata 0.8.0 64-bit (promoted)
Coiled 1.2 NoNNUE 64-bit
Mess 0.3.0 64-bit (promoted)

Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16069

**Comment by GrahamCCRL** [comment]
106TH AMATEUR SERIES (Division 9)

Lishex 1.1.1 64-bit (relegated)
Lynx 1.3.0 64-bit
Puffin 2.0.0 64-bit
RookieMonster 1.9.9 64-bit (relegated)
Myrddin 0.90 64-bit (2022-06) (relegated)
Lambergar 0.4.1 64-bit
Betsabe II 2023 64-bit (relegated)
Lux 4.1 64-bit
Luna 2.0.0 64-bit
Admete 1.5.0 64-bit (2022-05)
FoxSEE 8.2.0 64-bit
Fornax 4 64-bit
Prophet 4.3 64-bit
Ares 2.5 64-bit

Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16073

**Comment by GrahamCCRL** [comment]
---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Wed, Mar 6, 2024 at 5:47 PM
Subject: New Tournament
To: Duhamel Patrice ***@***.***>, Richard Pijl <
***@***.***>, ***@***.***>, ***@***.***>, <
***@***.***>, ***@***.***>


*PATRICIA AND THE JET*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
FirstMove.cgb book
12 minutes with 8 second increments.
4 cycles 44 rounds
All engines 1CPU (64-bit where available)


*Participants*

Ynode 0132 64-bit
Cheese 3.2.1 64-bit
The Baron 3.45 64-bit
Jet 1.1 64-bit
Patricia 1.0 64-bit
OliThink 5.10.5 64-bit
Clovis III 64-bit
Cheers 0.3.0 64-bit
Motor 0.1.0 64-bit
Seawall 20231015 64-bit
Pingu 3.0.0 64-bit
Odonata 0.80 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16074

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16074

Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
*THE PENGUIN AND THE PUFFIN*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 44 rounds
All engines 1CPU (64-bit where available)


*Participants*

Pingu 3.0.0 64-bit
Hiarcs Paderborn 2007
Odonata 0.8.0 64-bit
Lambergar 0.5.2 64-bit
Dumb 2.1 64-bit
Lynx 1.4.0 64-bit
Mess 0.3.0 64-bit
Puffin 3.0 64-bit
Nawito 22.07 64-bit
Fridolin 4.00 64-bit
CT800 1.45 64-bit
MadChess 3.2 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16068

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16068
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
*108TH AMATEUR SERIES (Division 7)*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 52 rounds
All engines 1CPU (64-bit where available)

*The top engine will be promoted and the bottom engine will be relegated.
Any other changes of division will be at my discretion and may not
necessarily involve playoff matches.*

*Participants*

4ku 4.0 64-bit *(relegated)*
Bagatur 4.1a 64-bit *(relegated)*
Francesca MAD 0.32 64-bit
Ynode 0133 64-bit
Cheese 3.2.1 64-bit
Kobra 1.1 64-bit *(promoted)*
ice4 4.0 64-bit *(relegated)*
tomitankChess 5.1 64-bit
The Baron 3.45 64-bit
OliThink 5.10.5 64-bit
Clovis III 64-bit
Inanis 1.2.0 64-bit *(promoted)*
Lambergar 0.5.2 64-bit *(promoted)*
Pingu 3.0.0 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16073

**Comment by GrahamCCRL** [comment]
---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Tue, Jun 11, 2024 at 8:13 PM
Subject: 109th Amateur Series Division 9
To: Erin Dame ***@***.***>, Rasmus%20Althoff%20 ***@***.***>,
Colin Jenkins ***@***.***>, Sam Roelants ***@***.***>,
Technochess ***@***.***>, Ernesto Torres ***@***.***>


*109TH AMATEUR SERIES (Division 9)*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 52 rounds
All engines 1CPU (64-bit where available)

*The top engine will gain automatic promotion, while the bottom engine
faces relegation. Any other changes of division will be at my discretion
and may not necessarily involve playoff matches.*

*Participants*

Coiled 1.2 NoNNUE 64-bit *(relegated)*
Puffin 3.0 64-bit *(relegated)*
Nawito 22.07 64-bit *(relegated)*
KnightX 4.0 64-bit *(relegated)*
Lux 4.2 64-bit
CT800 1.45 64-bit *(relegated)*
Arcanum 2.1 64-bit *(promoted)*
Boychesser 1.0 64-bit
Lozza 2.5 64-bit *(promoted)*
Yakka 1.0 64-bit *(relegated)*
Lishex 1.1.1 64-bit
Rengar 1.3.0 64-bit
RookieMonster 1.9.9 64-bit
Spaghet 1.0 Pesto 64-bit *(new)*


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16064

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16064
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Thu, Jun 13, 2024 at 12:44 AM
Subject: 109th Amateur Division 8
To: ***@***.***>, Charles Roberson ***@***.***>, <
***@***.***>, ***@***.***>, matthiaslang/jackychess <
***@***.***>, Erik <
***@***.***>


*109TH AMATEUR SERIES (Division 8 )*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 52 rounds
All engines 1CPU (64-bit where available)

*The top engine will be promoted and the bottom engine will be relegated.
Any other changes of division will be at my discretion and may not
necessarily involve playoff matches.*

*Participants*

OliThink 5.10.5 64-bit *(relegated)*
Ares 3.0.3 64-bit *(promoted)*
Clovis III 64-bit *(relegated)*
Dumb 2.1 64-bit
Inanis 1.2.0 64-bit *(relegated)*
Seawall 20231015 64-bit
Shallow 5.0 64-bit
Lynx 1.5.0 64-bit
Pingu 3.0.0 64-bit *(relegated)*
Belette 3.0.0 64-bit *(promoted)*
Elixir 1.0 64-bit *(new)*
JackyChess 24.04 64-bit *(promoted)*
Mess 0.3.0 64-bit
MadChess 3.2 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16071

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16071
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Sat, Jul 20, 2024 at 6:24 PM
Subject: 110th Amateur Series Division 8
To: ***@***.***>, ***@***.***>, ***@***.***>,
Charles Roberson ***@***.***>, matthiaslang/jackychess <
***@***.***>,
Technochess ***@***.***>


*110TH AMATEUR SERIES (Division 8 )*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
IM_4mvs.cgb book
12 minutes with 8 second increments.
4 cycles 52 rounds
All engines 1CPU

*The top engine will be promoted and the bottom engine will be relegated.
Any other changes of division will be at my discretion and may not
necessarily involve playoff matches.*

*Participants*

Francesca MAD 0.32 64-bit *(relegated)*
The Baron 3.45 64-bit *(relegated)*
OliThink 5.10.5 64-bit
Dumb 2.1 64-bit
Clovis III 64-bit
Ares 3.0.3 64-bit
Cheers 0.3.0 64-bit
Lynx 1.5.1 64-bit
Seawall 20231015 64-bit
Shallow 5.0 64-bit
Pingu 3.0.0 64-bit
JackyChess 24.04 64-bit
Mess 0.3.0 64-bit
KnightX 4.1 64-bit *(promoted)*


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16073

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16073
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
*BATTLE OF THE BIRDS II*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 44 rounds
All engines 1CPU


*Participants*

Pingu 3.0 64-bit
KnightX 4.1 64-bit
Illumina 1.0 64-bit
Jackychess 24.04 64-bit
Mess 0.3.0 64-bit
Puffin 3.0 64-bit
Lux 4.2 64-bit
Colossus 2022a 64-bit
Javelin 3.0.0 64-bit
Fridolin 4.0 64-bit
Nawito 22.07 64-bit
Yakka 1.0 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16067

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16067
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Sat, Aug 31, 2024 at 10:51 PM
Subject: 111th Amateur Series Division 8
To: Fons Bluemers ***@***.***>, Andres Valverde <
***@***.***>, Duhamel Patrice ***@***.***>,
Richard Pijl ***@***.***>, Charles Roberson <
***@***.***>, ***@***.***>, ***@***.***>, <
***@***.***>, matthiaslang/jackychess <
***@***.***>


*111TH AMATEUR SERIES (Division 8 )*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 52 rounds
All engines 1CPU

*The top engine will be promoted and the bottom engine will be relegated.
Any other changes of division will be at my discretion and may not
necessarily involve playoff matches.*

*Participants*

Dirty Duna 64-bit *(new)*
Pingu 4.0.0 64-bit
Lynx 1.6.0 64-bit
Cheese 3.2.1 64-bit *(relegated)*
The Baron 3.45 64-bit
Arcanum 2.2 64-bit *(relegated)*
Ares 3.0.3 64-bit
Heimdall 0.4 64-bit *(promoted)*
Dumb 2.1 64-bit
OliThink 5.10.5 64-bit
Clovis III 64-bit
Cheers 0.3.0 64-bit
Seawall 20231015 64-bit
JackyChess 24.04 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16068

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16068
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
*112TH AMATEUR SERIES (Division 7)*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 52 rounds
All engines 1CPU

*The top engine will be promoted and the bottom engine will be relegated.
Any other changes of division will be at my discretion and may not
necessarily involve playoff matches.*

*Participants*

Lambergar 0.6.0 64-bit *(relegated)*
Mida 2.3.1 64-bit *(relegated)*
Atlas 4.35 64-bit *(relegated)*
Orion 1.0 64-bit *(relegated)*
Lynx 1.7.0 64-bit *(promoted)*
Roc 2.0.3 64-bit
Heimdall 1.0.0 64-bit
Kobra 1.2 64-bit
Cheers 1.0.0 64-bit *(dav)*
Wahoo 4.0 64-bit
Arcanum 2.3.1 64-bit *(promoted)*
Pingu 4.0.0 64-bit *(promoted)*
Dirty Duna 64-bit *(promoted)*
Ares *(new version)*


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16065

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16065
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
*LYNX ON THE PROWL*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 44 rounds
All engines 1CPU


*Participants*

Roc 2.0.3 64-bit
Lynx 1.7.0 64-bit
Arcanum 2.3.1 64-bit
Lambergar 0.6.0 64-bit
Orion 1.0 64-bit
Perseus 0.9-alpha 64-bit
Kobra 1.2 64-bit
Wahoo 4.0 64-bit
EveAnn 2.1 64-bit
ice4 5.0 64-bit
4ku 5.0 64-bit
Pingu 4.0.0 1.0 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16064

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16064
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Mon, Dec 16, 2024 at 7:45 AM
Subject: New Tournament
To: Andres Valverde ***@***.***>, Dany Anulliero <
***@***.***>, John Merlino ***@***.***>, Lars
Hallerström ***@***.***>, ***@***.***>, Üstün
Engin ***@***.***>


WOLF IN SHEEPS CLOTHING

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 44 rounds

Isa 3.9 64-bit
Lambergar 0.6.0 64-bit
Lynx 1.7.0 64-bit
EveAnn 2.1 64-bit
Myrddin 0.92 64-bit
Amoeba 3.4 64-bit
Tornado 9.0 64-bit
ChandraChess 2.0 64-bit
Puffin 5.0 64-bit
Inanis 1.5.0 64-bit
Jackal 1.1.0 64-bit
Pingu 4.0.0 64-bit

Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16072

**Comment by GrahamCCRL** [comment]
114TH AMATEUR SERIES (Division 8 )

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 52 rounds

Roc 2.0.4 64-bit (relegated)
Isa 3.9 64-bit (promoted)
Perseus 0.9-alpha 64-bit (relegated)
EveAnn 2.2 64-bit
Orion 1.0 64-bit (relegated)
Wahoo 4.0 64-bit (relegated)
ice4 5.0 64-bit (relegated)
Pingu 4.0.0 64-bit (relegated)
Jackal 1.2.0 64-bit (new)
Dirty Duna 64-bit
4ku 5.1 64-bit
Cheers 1.0.0 64-bit
Inanis 1.5.0 64-bit
Ceibo 1.0 64-bit

Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16071
