### ISSUE TITLE
can't compile on Linux : std::chrono with C++20 ?

### ISSUE THREAD

**Issue by tissatussa** [WillChing01/Pingu#132]
while compiling a clone of your newest source code i get errors :

```
include/uci.h: In function ‘void gensfenCommand(Board&, const std::vector<std::__cxx11::basic_string<char> >&)’:
include/uci.h:276:33: error: ‘format’ is not a member of ‘std’; did you mean ‘fmt::v8::format’?
  276 |     std::string dateTime = std::format("{:%F_%H-%M-%S_%Z}",
```

```
include/uci.h: In function ‘void gensfenCommand(Board&, const std::vector<std::__cxx11::basic_string<char> >&)’:
include/uci.h:278:22: error: ‘zoned_time’ is not a member of ‘std::chrono’
  278 |         std::chrono::zoned_time{
```

i solved the first error by replacing your `#include <format>` in `uci.h` by :

`#include <fmt/format.h>`

because on my Xubuntu 22.04 i seem to have `libfmt` installed (see https://github.com/fmtlib/fmt ), so the compiler suggestion _did you mean ‘fmt::v8::format’?_ was my solution.

but i can't solve the second error .. i guess some options in makefile are wrong or missing .. i have default g++-11 and i can even use g++-12, but they fail .. searching for answers, i also tried to change the option `-std=gnu++20` into other 'values' but i don't succeed .. it seems `std::chrono::zoned_time` is a modern construct for C++20, but how to activate this on my Linux notebook ?

**Comment by WillChing01** [comment]
Hi, have you tried using g++-13? I think it has support for format and std::chrono::zoned_time.

**Comment by tissatussa** [comment]
thanks ! it seems g++13 is rather new and Ubuntu 22.04 is LTS, so it won't have g++-13 .. this will be in 23.04 .. but i found _Do you know/think if g++-13 is coming to Ubuntu 22?_ at https://bityl.co/NJCt - here a user shared this info :

_actually there's gcc\g++ 13 for 22.04 in_ `ppa:ubuntu-toolchain-r/test`

this way i installed g++-13 with apt (by Synaptic) and after changing the makefile accordingly the compilation went OK and this version run fine in CuteChess !
