### ISSUE TITLE
Version numbering

### ISSUE THREAD

**Issue by SzotsGabor** [WillChing01/Pingu#58]
Hi William,

If you intend to continue developing your engine and release further versions, which I hope, I suggest including version number in the exe name and UCI id to avoid confusion.

Some questions:
By your estimation how strong is your engine?
Where are you from? We like to include nationality of authors in our lists but it's OK if you prefer not to tell.

Gabor Szots
CCRL testing group

**Comment by SzotsGabor** [comment]
It is impossible to test Pingu for our list while various releases cannot be distinguished.

**Comment by WillChing01** [comment]
Hi Gabor,

The first version of Pingu has now been released, [Pingu 1.0.0](https://github.com/WillChing01/Pingu/releases/tag/v1.0.0), and its estimated rating is ~2200, derived from 10s + 0.1s/move matches with other engines.

Further releases will be labelled similarly, and I will also maintain a pre-release 'dev-build' which will contain the very latest updates.

Also, I am from the UK.

Many thanks,

William

**Comment by SzotsGabor** [comment]
Now that all is well I have started a tournament for the CCRL blitz list.
